server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service #eureka 服务端实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心  我的职责就是维护服务实例 并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
        #  uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
         # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
           # - After=2022-01-05T19:56:35.294+08:00[Asia/Shanghai]
           # - Before=2022-01-05T19:56:35.294+08:00[Asia/Shanghai]
           # - Between=2022-01-05T19:50:35.294+08:00[Asia/Shanghai],2022-01-05T19:56:35.294+08:00[Asia/Shanghai]
           # - Cookie=username,yyyy
           # - Header=X-Request-Id, \d+
           # - Host=**.guigu.com
           # - Method=GET
           # - Query=username, \d+ #要有参数名 值是正数